import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GlobalProvider } from "./(context)/GlobalState";
import Header from "./(components)/Header";
import Footer from "./(components)/Footer";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <GlobalProvider>
          <GoogleOAuthProvider clientId={process.env.GOOGLE_API_TOKEN}>
            <Header />
            <div className="max-w-screen-xl mx-auto lg:px-0 md:p-4 md:py-8">
              {children}
            </div>
            <Footer />
          </GoogleOAuthProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
